// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';

/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAggQbjh12COsbBt55-lv49K0GF7RV0bBM',
    appId: '1:263579544076:web:15d93f8564f1466da31c29',
    messagingSenderId: '263579544076',
    projectId: 'fitsync-76aaf',
    authDomain: 'fitsync-76aaf.firebaseapp.com',
    storageBucket: 'fitsync-76aaf.firebasestorage.app',
    measurementId: 'G-E9NPGXT7M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCWWOnqF11RU9aFZIybmKx0ERabmhdLI4',
    appId: '1:263579544076:android:d10712324f110f0aa31c29',
    messagingSenderId: '263579544076',
    projectId: 'fitsync-76aaf',
    storageBucket: 'fitsync-76aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBALUBdlrw0kw87WoUysbj37FONvBlRU9w',
    appId: '1:263579544076:ios:cb17174d85d8e3c8a31c29',
    messagingSenderId: '263579544076',
    projectId: 'fitsync-76aaf',
    storageBucket: 'fitsync-76aaf.firebasestorage.app',
    iosBundleId: 'com.example.fitsyncgemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBALUBdlrw0kw87WoUysbj37FONvBlRU9w',
    appId: '1:263579544076:ios:cb17174d85d8e3c8a31c29',
    messagingSenderId: '263579544076',
    projectId: 'fitsync-76aaf',
    storageBucket: 'fitsync-76aaf.firebasestorage.app',
    iosBundleId: 'com.example.fitsyncgemini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAggQbjh12COsbBt55-lv49K0GF7RV0bBM',
    appId: '1:263579544076:web:ad94b0a3afbf909ca31c29',
    messagingSenderId: '263579544076',
    projectId: 'fitsync-76aaf',
    authDomain: 'fitsync-76aaf.firebaseapp.com',
    storageBucket: 'fitsync-76aaf.firebasestorage.app',
    measurementId: 'G-CJHFG0RX3W',
  );
}
