import aiohttp
import asyncio
import base64
import json
from typing import Dict, List, Optional
from app.core.config import settings
from app.utils.rate_limiter import rate_limiter
from fastapi import HTTPException

class FreeVirtualTryOnClient:
    def __init__(self):
        self.huggingface_token = getattr(settings, 'HUGGINGFACE_TOKEN', None)
        self.base_url = "https://api-inference.huggingface.co/models"
        self.model_id = "akhaliq/virtual-try-on"  # Replace with your chosen model
        
    async def virtual_tryon(
        self, 
        person_image: bytes, 
        clothing_image: bytes, 
        user_id: str,
        tryon_type: str = "full_body"
    ) -> Dict:
        """
        Perform virtual try-on using free Hugging Face models
        
        Args:
            person_image: User's photo as bytes
            clothing_image: Clothing item image as bytes
            user_id: User identifier for rate limiting
            tryon_type: "upper_body", "lower_body", or "full_body"
        """
        
        # Check rate limit
        allowed, reset_time = await rate_limiter.check_rate_limit(
            "free_virtual_tryon", 
            20,  # 20 requests per hour (free tier)
            3600,
            user_id
        )
        
        if not allowed:
            raise HTTPException(
                status_code=429,
                detail=f"Free virtual try-on rate limit exceeded. Reset at {reset_time}"
            )
        
        # Prepare payload for Hugging Face API
        headers = {
            "Authorization": f"Bearer {self.huggingface_token}",
            "Content-Type": "application/json"
        }
        payload = {
            "inputs": {
                "person_image": base64.b64encode(person_image).decode("utf-8"),
                "clothing_image": base64.b64encode(clothing_image).decode("utf-8"),
                "tryon_type": tryon_type
            }
        }

        async with aiohttp.ClientSession() as session:
            async with session.post(
                f"{self.base_url}/{self.model_id}",
                headers=headers,
                data=json.dumps(payload)
            ) as response:
                if response.status != 200:
                    detail = await response.text()
                    raise HTTPException(
                        status_code=response.status,
                        detail=f"Hugging Face API error: {detail}"
                    )
                result = await response.json()

        # Parse the result (assume result contains 'result_image' as base64)
        result_image_b64 = result.get("result_image")
        confidence_score = result.get("confidence_score", 0.75)
        processing_time_ms = result.get("processing_time_ms", 2000)
        quality_metrics = result.get("quality_metrics", {})

        return {
            "success": True,
            "result_image": f"data:image/png;base64,{result_image_b64}",
            "confidence_score": confidence_score,
            "processing_time_ms": processing_time_ms,
            "tryon_type": tryon_type,
            "quality_metrics": quality_metrics,
            "note": "Result generated by Hugging Face virtual try-on model"
        }
    
    async def analyze_style_compatibility(
        self, 
        item1_image: bytes, 
        item2_image: bytes,
        user_id: str
    ) -> Dict:
        """Analyze style compatibility between two clothing items"""
        
        # Rate limiting
        allowed, _ = await rate_limiter.check_rate_limit(
            "free_style_analysis", 
            30,  # 30 requests per hour
            3600,
            user_id
        )
        
        if not allowed:
            return {"success": False, "error": "Rate limit exceeded"}
        
        # Simulate style analysis
        return {
            "success": True,
            "compatibility_score": 0.7,
            "style_harmony": 0.7,
            "color_coordination": 0.7,
            "recommendations": [
                "Items appear to be compatible",
                "Consider adding accessories",
                "Colors work well together"
            ]
        }

# Create global instance
free_virtual_tryon_client = FreeVirtualTryOnClient()
